name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
            artifact_name: merger
            asset_name: merger-linux-x86_64
          - os: ubuntu-latest
            target: aarch64-linux
            artifact_name: merger
            asset_name: merger-linux-aarch64
          - os: windows-latest
            target: x86_64-windows
            artifact_name: merger.exe
            asset_name: merger-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-macos
            artifact_name: merger
            asset_name: merger-macos-x86_64
          - os: macos-latest
            target: aarch64-macos
            artifact_name: merger
            asset_name: merger-macos-aarch64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1

    - name: Build for target
      run: |
        zig build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.target }}

    - name: Copy binary (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cp zig-out/bin/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

    - name: Copy binary (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        copy zig-out\bin\${{ matrix.artifact_name }} ${{ matrix.asset_name }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
